### ISSUE TITLE
Need some design ideas to merge

### ISSUE THREAD

**Issue by Garv-it2002** [gdsc-bit/Design-Book#6]
https://github.com/gdsc-bit/Design-Book/blob/main/Creative%20design%20ideas

**Comment by Garv-it2002** [comment]
Please add your work in this format.

{
  "id": 1,
  "Description": "Create a software which can monitor hobbies of a person.",
},

**Comment by akashgreninja** [comment]
??

**Comment by akshathar-navada** [comment]
@Garv-it2002  Can you assign this issue to me?

**Comment by Garv-it2002** [comment]
> @Garv-it2002 Can you assign this issue to me?

https://github.com/gdsc-bit/Design-Book/blob/main/Creative%20design%20ideas add your idea in this actually the issue is open for everyone and it will remain open after that.
